import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { Page } from "@/components/page"
import { cn } from "@/shared/clsx"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Test app for Yoldi",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ru" className="h-full">
      <body className={cn("h-full bg-white text-black", inter.className)}>
        <Page>{children}</Page>
      </body>
    </html>
  )
}
